# Moment models fine-tune analysis | Mask test
> This notebook is the pre-analysis of moment models to select the cases used in the paper.

# RECORDATORIO 
1) Conseguir que compilen de nuevo
2) Enmascarar también en evaluación, no solo en training, majaretilla...

In [1]:
# Input parameters
model_patch_size = 8
verbose          = 0
reset_kernel     = False

In [2]:
#! pip install --no-deps ydata_profiling
#! pip install --no-deps dacite
#! pip install --no-deps multimethod
#! pip install --no-deps visions
#! pip install --no-deps wordcloud
#! pip install --no-deps imagehash
#! pip install --no-deps htmlmin

In [3]:
# Imports
from dvats.all import *
from tsai.data.preparation import SlidingWindow
from fastcore.all import *
import wandb
wandb_api = wandb.Api()
from yaml import load, FullLoader
import dvats.utils as ut
from dvats.imports import beep
import pandas as pd
from copy import deepcopy
import matplotlib.pyplot as plt
import ydata_profiling as ydp
import seaborn as sns

/usr/local/share/miniconda3/envs/env/lib/python3.10/site-packages/aeon/base/__init__.py:24: FutureWarning: The aeon package will soon be releasing v1.0.0 with the removal of legacy modules and interfaces such as BaseTransformer and BaseForecaster. This will contain breaking changes. See aeon-toolkit.org for more information. Set aeon.AEON_DEPRECATION_WARNING or the AEON_DEPRECATION_WARNING environmental variable to 'False' to disable this warning.
  warnings.warn(

Octave is ready <oct2py.core.Oct2Py object at 0x7f2be4876500>

In [4]:
import torch
torch.cuda.set_device(0)
#torch.cuda.set_device(1)

In [5]:
from fastai.losses import MSELossFlat
from dvats.encoder import MAELossFlat, EvalMSE, EvalRMSE, EvalMAE, EvalSMAPE
import dvats.config as cfg_
import gc
import os

### Setting up Weight & Biases information

In [6]:
# User and project
entity = os.environ.get("WANDB_ENTITY")
project = os.environ.get("WANDB_PROJECT")
folder = entity+'/'+project+'/'

# Dataset
dataset = 'gtrends_kohls'
dataset_version = 'v2'

#dataset = 'S1'
#dataset_version = 'v8'

enc_artifact_dataset = folder + dataset + ':' + dataset_version

# Models
model_family = 'zeroshot-moment'
task = 'embedding'
enc_artifact_small_name = folder + model_family + '-small-' + task + ':v0'
enc_artifact_base_name  =  folder + model_family + '-base-' + task + ':v0'
enc_artifact_large_name = folder + model_family + '-large-' + task + ':v0'

In [7]:
enc_artifact_small_name

'mi-santamaria/deepvats/zeroshot-moment-small-embedding:v0'

### Download dataset

In [8]:
print("Getting dataset artifact: ", enc_artifact_dataset)
df_artifact = wandb_api.artifact(enc_artifact_dataset, type = 'dataset')

Getting dataset artifact:  mi-santamaria/deepvats/gtrends_kohls:v2

In [9]:
print(df_artifact.name)
df = df_artifact.to_df()
display(df.head())
df.shape

gtrends_kohls:v2

wandb:   1 of 1 files downloaded.

              volume
2004-01-01  0.010417
2004-01-08  0.010417
2004-01-15  0.010417
2004-01-22  0.000000
2004-01-29  0.000000

(440, 1)

### Encoder Input

In [10]:
#enc_input, _ = SlidingWindow(window_len=17, stride=2, get_y=[])(df)
#enc_input.shape
enc_input = df

### Functions

In [11]:
def count_parameters(model):
    #return sum(p.numel() for p in model.parameters() if p.requires_grad)
    return sum(p.numel() for p in model.parameters())

def greater_than(lst, val):
    vals = []
    for x in lst:
        try:
            x = int(x)
            if (x > val): 
                vals.append(x)
        except:
            continue
    return vals
    #return [ x for x in lst if isinstance(x, int) and x > val]

In [12]:
def plot_with_multiple_secondary_y(df, primary_vars, secondary_vars, figsize=(12, 6)):
    """
    Plots multiple variables with different scales on primary and secondary y-axes.

    Parameters:
    - df (pd.DataFrame): The DataFrame containing the data.
    - primary_vars (list): Variables to plot on the primary y-axis.
    - secondary_vars (list): Variables to plot on the secondary y-axis.
    - figsize (tuple): Size of the figure.

    Returns:
    - None: Displays the plot.
    """
    ax = df[primary_vars + secondary_vars].plot(
        secondary_y=secondary_vars, figsize=figsize
    )
    ax.set_title("Variables with Primary and Secondary Axes")
    plt.show()

In [13]:
def plot_correlation(profile, figsize=(8, 6)):
    correlation_matrix = profile.corr()
    # Crear el heatmap con seaborn
    plt.figure(figsize = figsize)  # Ajusta el tamaño si es necesario
    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0, vmin=-1, vmax=1)
    plt.title("Correlation Matrix")
    plt.show()

### Common Fine-tune args

In [14]:
import dvats.config as cfg_
user, project, version, data, config, job_type = cfg_.get_artifact_config_MVP(False)

In [15]:
print(config['batch_size'])
print(config['r'])
print(config['analysis_mode'])

16
0.4
online

In [16]:
config['r'] = 1e-3 #1e-6
config['r']

0.001

In [17]:
config['norm_use_single_batch']

False

In [18]:
#! pip install tslearn

In [19]:
from tslearn.metrics import SoftDTWLossPyTorch

In [20]:
common_args = {
    "X": df,
    "stride": 1,
    "batch_size": config['batch_size'],
    "cpu": False,
    "to_numpy": False,
    "time_flag": True,
    "n_windows": None,
    "n_windows_percent": None,
    "shot": True,
    "eval_pre": True,
    "eval_post": True,
    "lr": config['r'], #use enc_run lr,
    "lr_scheduler_flag": True, # False
    "lr_scheduler_name": "cosine_with_restarts",
    "lr_scheduler_num_warmup_steps": 100, # None
    "window_sizes": [12],
    "full_dataset": True,
    "window_sizes_offset": 0.05,
    "windows_min_distance": 0, #int(np.ceil(1.5*enc_input.shape[0]/100)),
    "print_to_path": True,
    "print_both": False,
    "print_path": "./logs.txt",
    "print_mode": "a",
    "use_moment_masks": True,
    "mask_stateful": config['mask_stateful'],
    "mask_future": config['mask_future'],
    "mask_sync": config['mask_sync'],
    "analysis_mode": config['analysis_mode'],
    "use_wandb": config['use_wandb'],
    "norm_by_sample": config['norm_by_sample'],
    "norm_use_single_batch": config['norm_use_single_batch'],
    "show_plot": True,
    "metrics": [EvalMSE, EvalRMSE, EvalMAE, EvalSMAPE],
    "metrics_args": [{'squared': False}, {'squared': True}, {}, {}],
    "metrics_names":["mse", "rmse", "mae", "smape"],
    "metrics_dict": None,
    #"criterion": torch.nn.MSELoss(),
    # Segmentation
    "criterion": SoftDTWLossPyTorch(gamma=5.0, normalize = True, dist_func = None),
    "mix_windows": True
}

In [21]:
common_args["windows_min_distance"]

0

### Cases execution function

In [22]:
from momentfm.utils.masking import Masking

In [23]:
def cases_loop(
    model, 
    n_epochs_list, 
    dataset_percents, 
    masked_percents, 
    n_sizes_list, 
    summarized = True, 
    do_beep = True, 
    verbose = 1,
    save = True,
    file_errors = "",
    file_results = ""
):
    mssg = ut.Mssg(verbose = verbose, level = -1)
    result_columns = [
        'model_size','n_epochs','dataset_percent','masked_percent','n_windows', 
        'time',
        'first_train_loss','first_mse','first_rmse','first_mae','first_smape', 
        'last_train_loss','last_mse','last_rmse','last_mae','last_smape'
    ]
    result_columns = result_columns if summarized else result_columns + ['losses','eval_results_pre','eval_results_post']
    results = pd.DataFrame(columns = result_columns)
    
    errors = pd.DataFrame(
        columns = [
            'model_size',
            'n_epochs',
            'dataset_percent',
            'masked_percent',
            'n_windows',
            'windows',
            'error'
        ]
    )
    model_backup = deepcopy(model)
    i = 0
    for n_epochs in n_epochs_list:
        for dataset_percent in dataset_percents:
            print(dataset_percent)
            for masked_percent in masked_percents:
                model.mask_generator = Masking(mask_ratio = masked_percent)
                for sizes in n_sizes_list:
                    print(f"--> epoch {n_epochs}, dataset_percent {dataset_percent}, mask {masked_percent}")
                    redmssg = f" sizes {sizes}"
                    redmssg = f"\033[91m{redmssg}\033[0m"
                    print(redmssg)

                    print(f"Cuda memmory allocated: {torch.cuda.memory_allocated()}")
                    model_case = deepcopy(model_backup)
                    case = {
                            'model_size': "small",
                            'n_epochs': n_epochs,
                            'dataset_percent': dataset_percent,
                            'masked_percent': masked_percent,
                            'n_windows': sizes,
                            'windows': None
                           }
                    result_dict = deepcopy(case)
                    error_dict = deepcopy(case)
                    error = False
                    print(1-dataset_percent)
                    torch.cuda.synchronize()
                    result = fine_tune(
                        enc_learn           = model_case,
                        window_mask_percent = masked_percent,
                        training_percent    = dataset_percent,
                        validation_percent  = 0.3,
                        num_epochs          = n_epochs,
                        n_window_sizes      = sizes,
                        verbose             = verbose,
                        register_errors     = True,
                        save_best_or_last   = True, # only available for moment,
                        #force_best_lr       = True,
                        **common_args    
                    )
                    common_args['print_mode']='a'

                    default_error = pd.DataFrame([{
                        'model_size': case['model_size'], 
                        'n_epochs': case['n_epochs'],
                        'dataset_percent': case['dataset_percent'],
                        'masked_percent': case['masked_percent'],
                        'n_windows': sizes,
                        'windows': "Unknown",
                        'error': 'Non registered error',
                        'window': "Unknown"
                    }])

                    try:
                        print("---- Returned internal errors ---")
                        internal_errors = result[10]
                        
                    except:
                        internal_errors = default_error
            
                    print("Check:", result[0])
                    if len(result[0]) > 0:
                    
                        result_dict.update({
                            'time'             : result[4],
                            'windows'          : result[8].cpu() if isinstance(result[8], torch.Tensor) else result[8],
                            'first_train_loss' : result[0][0][0].cpu().item() if torch.is_tensor(result[0][0][0]) else result[0][0][0],
                            'last_train_loss'  : result[0][-1][-1].cpu().item() if torch.is_tensor(result[0][-1][-1]) else result[0][-1][-1],
                            'best_epochs'       : result[9],
                            'train_losses'      : result[0][0],
                            'eval_pre'          : result[1],
                            'eval_post'         : result[2],
                            'full_result'       : result
                        })
                        if result[1] == {}:
                            result_dict.update({
                                'first_eval_loss'  : np.nan,
                                'first_mse'        : np.nan,
                                'first_rmse'       : np.nan,
                                'first_mae'        : np.nan
                            })
                        else:
                            print("N windows: ", len(result[8]))
                            print("Loss: ", result[1]['loss'])
                            result_dict.update({
                                'first_eval_loss'  : result[1]['loss'][-1].cpu().item() if torch.is_tensor(result[1]['loss']) else result[1]['loss'][-1],
                                'first_mse'        : result[1]['mse'][-1].cpu().item() if torch.is_tensor(result[1]['mse']) else result[1]['mse'][-1],    
                                'first_rmse'       : result[1]['rmse'][-1].cpu().item() if torch.is_tensor(result[1]['rmse']) else result[1]['rmse'][-1],
                                'first_mae'        : result[1]['mae'][-1].cpu().item() if torch.is_tensor(result[1]['mae']) else result[1]['mae'][-1],                                
                                'first_smape'      : result[1]['smape'].cpu().item() if torch.is_tensor(result[1]['smape']) else result[1]['smape']
                            })
                        if result[2] == {}:
                            result_dict.update({
                                'last_eval_loss'  : np.nan,
                                'last_mse'        : np.nan,
                                'last_rmse'       : np.nan,
                                'last_mae'        : np.nan
                            })
                        else:
                            result_dict.update({
                                'last_eval_loss'   : result[2]['loss'][-1].cpu().item() if torch.is_tensor(result[2]['loss'][-1]) else result[2]['loss'][-1],
                                'last_mse'         : result[2]['mse'][-1].cpu().item() if torch.is_tensor(result[2]['mse'][-1]) else result[2]['mse'][-1],
                                'last_rmse'        : result[2]['rmse'][-1].cpu().item() if torch.is_tensor(result[2]['rmse'][-1]) else result[2]['rmse'][-1],
                                'last_mae'         : result[2]['mae'][-1].cpu().item() if torch.is_tensor(result[2]['mae'][-1]) else result[2]['mae'][-1],
                                'last_smape'       : result[2]['smape'][-1].cpu().item() if torch.is_tensor(result[2]['smape'][-1]) else result[2]['smape'][-1]
                            })
                            
        
                        if not summarized:
                            result_dict.update({
                                'losses'           : [[v.cpu().item() if torch.is_tensor(v) else v for v in loss] for loss in result[0]],
                                'eval_results_pre' : {k: v.cpu().item() if torch.is_tensor(v) else v for k, v in result[1].items()},
                                'eval_results_post': {k: v.cpu().item() if torch.is_tensor(v) else v for k, v in result[2].items()},
                                })  
                        results = pd.concat([results, pd.DataFrame([result_dict])], ignore_index=True)
                    else:
                        print(f"Failed case | N Errors {errors.shape[0]} | N Results { results.shape[0] }")
                        # Attach possible errors
                        internal_errors['model_size'] = case['model_size']
                        internal_errors['n_epochs'] = case['n_epochs']
                        internal_errors['dataset_percent'] = case['dataset_percent']
                        internal_errors['masked_percent'] = case['masked_percent']
                        internal_errors['windows'] = [result[8]]*len(internal_errors)
                        print("--- Internal ---")
                        if (internal_errors.empty):
                            print("Returned errors empty")
                            internal_errors = default_error
                        display(internal_errors)
                        errors = pd.concat([errors, internal_errors])
                        print("--- Concatenated ---")
                        display(errors)
                        print(f"Failed case | N Errors {errors.shape[0]} | N Results { results.shape[0] } ")
                    if not error: mssg.print_error(f" case {case} | time: {result[4]}")
                    before = torch.cuda.memory_allocated()
                    model_case = None
                    gc.collect()
                    torch.cuda.empty_cache()
                    display(results)
                    if do_beep:
                        beep(1)
                    mssg.print(f"epoch {n_epochs}, dataset_percent {dataset_percent}, mask {masked_percent}, sizes {sizes} -->")
                if save:
                    mssg.print(f"Update results into {file_results}")
                    results.to_csv(file_results, index = False, header = True)
                    mssg.print(f"Update errors into {file_errors}")
                    errors.to_csv(file_errors, index = False, header = True)
                if do_beep:
                    beep(2)
                    beep(2)
                mssg.print(f"epoch {n_epochs}, dataset_percent {dataset_percent}, mask {masked_percent} -->")
            if do_beep:
                beep(3)
                beep(3)
                beep(3)
            mssg.print(f"epoch {n_epochs}, dataset_percent {dataset_percent}-->")
        if do_beep:
            beep(4)
            beep(4)
            beep(4)
            beep(4)
        mssg.print(f"epoch {n_epochs}-->")
    if do_beep:
        beep(1000)
        beep(1000)
        beep(1000)
        beep(1000)
        beep(1000)
    model_backup = None
    gc.collect()
    torch.cuda.empty_cache()
    return results, errors

# Analysis

## Defining full reasonable values

The following parameters are modified within the fine-tuning:
- `n_epochs_list` is used to set up the number of epochs used in the training step.
- `dataset_percents` is used to select the percentage of the dataset used for each case fine-tuning.
- `masked_percents` is used to select the  percentage of the training dataset we want to mask for the model to fill it up.
- `sizes` is used to select the number of window sizes we want to use for the fine-tuning.

In [24]:
n_epochs_list     = [5, 10, 20]
dataset_percents  = [0.25, 0.5, 0.75, 1] #1 No tendría sentido porque sería como hacer lo mismo que con mvp. entrenar con todo el dataset.
masked_percents = [0.25, 0.5, 0.75]
sizes             = [1, 5]
total_cases_small = len(n_epochs_list)*len(dataset_percents)*len(masked_percents)*len(sizes)
print(f"Total cases: {total_cases_small}")

Total cases: 72

### Moment-Small
Getting the results for moment small.

#### Download the model

In [25]:
already_computed_small = False
#file_errors_small  = 'errors_small_29012025_1.csv'
#file_results_small = 'results_small_29012025_1.csv'
#file_errors_small  = 'errors_small_03022025_2.csv'
#file_results_small = 'results_small_03022025_2.csv'
#file_errors_small  = 'errors_small_06022025_1.csv'
#file_results_small = 'results_small_06022025_1.csv'
file_errors_small  = 'errors_small_07022025_1.csv'
file_results_small = 'results_small_07022025_1.csv'
file_errors_small  = 'errors_small_10022025_1.csv'
file_results_small = 'results_small_10022025_1.csv'
file_errors_small  = 'errors_small_11022025_2.csv'
file_results_small = 'results_small_11022025_2.csv'
file_errors_small  = 'errors_small_11022025_3.csv'
file_results_small = 'results_small_11022025_3.csv'
file_errors_small  = 'errors_small_11022025_4.csv'
file_results_small = 'results_small_11022025_4.csv'
file_errors_small  = 'errors_small_12022025_1.csv'
file_results_small = 'results_small_12022025_1.csv'
file_errors_small  = 'errors_small_12022025_2.csv'
file_results_small = 'results_small_12022025_2.csv'
file_errors_small  = 'errors_small_14022025_2.csv' #e-4
file_results_small = 'results_small_14022025_2.csv'
file_errors_small  = 'errors_small_14022025_3.csv' # e-3
file_results_small = 'results_small_14022025_3.csv'
file_errors_small  = 'errors_small_17022025_3.csv' # lr_find --- no conseguido # lr_optimizer
file_results_small = 'results_small_17022025_3.csv'

file_errors_small  = 'errors_small_25022025_3.csv' 
file_results_small = 'results_small_25022025_3.csv'

file_errors_small  = 'errors_small_26022025_1' 
file_results_small = 'results_small_26022025_1'
file_errors_small  = 'errors_small_03032025_1' 
file_results_small = 'results_small_03032025_1'

file_results_small = 'results_small_dtw_segmentation_1'
file_errors_small = 'errors_small_dtw_segmentation_2'
file_errors_small = file_errors_small+dataset+version+".csv"
file_results_small = file_results_small+dataset+version+".csv"

In [26]:
print("Getting small artifact: ", enc_artifact_small_name)
enc_artifact_small = wandb_api.artifact(enc_artifact_small_name, type='learner')
print(enc_artifact_small.name)
moment_small = enc_artifact_small.to_obj()

Getting small artifact:  mi-santamaria/deepvats/zeroshot-moment-small-embedding:v0
zeroshot-moment-small-embedding:v0

wandb: Downloading large artifact zeroshot-moment-small-embedding:v0, 144.63MB. 1 files...
wandb:   1 of 1 files downloaded.
Done. 0:0:0.5

In [27]:
moment_small.head.linear.out_features

8

### Specific parameters

In [28]:
n_epochs_list_small    = [20]
dataset_percents_small = [0.15, 0.2,0.25, 0.3]
masked_percents_small  = [0.25, 0.5, 0.75]
sizes_small            = [1, 2, 4, 6, 8, 10]
#sizes_small            = [6, 8, 10]
total_cases_small      = len(n_epochs_list_small)*len(dataset_percents_small)*len(masked_percents_small)*len(sizes_small)
print(f"Total cases: {total_cases_small}")

Total cases: 72

### Execute!

In [29]:
? moment_small

Signature:        moment_small(*args, **kwargs) -> momentfm.data.base.TimeseriesOutputs
Type:            MOMENTPipeline
String form:
MOMENTPipeline(
           (normalizer): RevIN()
           (tokenizer): Patching()
           (patch_embedding): PatchEmbed <...> pout(p=0.1, inplace=False)
           (linear): Linear(in_features=512, out_features=8, bias=True)
           )
           )
File:            /usr/local/share/miniconda3/envs/env/lib/python3.10/site-packages/momentfm/models/moment.py
Docstring:       <no docstring>
Class docstring:
Base class for all neural network modules.

Your models should also subclass this class.

Modules can also contain other Modules, allowing to nest them in
a tree structure. You can assign the submodules as regular attributes::

    import torch.nn as nn
    import torch.nn.functional as F

    class Model(nn.Module):
        def __init__(self) -> None:
            super().__init__()
            self.conv1 = nn.Conv2d(1, 20, 5)
            self.conv2 = nn.Conv2d(20, 20, 5)

        def forward(self, x):
            x = F.relu(self.conv1(x))
            return F.relu(self.conv2(x))

Submodules assigned in this way will be registered, and will have their
parameters converted too when you call :meth:`to`, etc.

.. note::
    As per the example above, an ``__init__()`` call to the parent class
    must be made before assignment on the child.

:ivar training: Boolean represents whether this module is in training or
                evaluation mode.
:vartype training: bool
Init docstring:  Initialize internal Module state, shared by both nn.Module and ScriptModule.

In [ ]:
results_small      = None
errors_small       = None
if already_computed_small:
    results_small = pd.read_csv(
        file_results_small, 
        index_col= None, 
        header   =0
    )
    errors_small  = pd.read_csv(
        file_errors_small, 
        index_col = None, 
        header    =0
    )
else:
    results_small, errors_small = cases_loop(
        model             = moment_small, 
        n_epochs_list     = n_epochs_list_small, 
        dataset_percents  = dataset_percents_small, 
        masked_percents = masked_percents_small, 
        n_sizes_list      = sizes_small, 
        verbose           = 1,
        summarized        = True,
        save              = True,
        file_errors       = file_errors_small,
        file_results      = file_results_small
    )
    #already_computed_small = True

0.15
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 1
Cuda memmory allocated: 0
0.85
Initialize Windowed Dataset

100% 16/16 [00:14<00:00,  1.11it/s]
100% 140/140 [01:20<00:00,  1.75it/s]
100% 16/16 [00:10<00:00,  1.59it/s]

---- Returned internal errors ---
Check: [[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]]
N windows:  1
Loss:  [0.05564203326503048]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 1, 'windows': None} | time: 80.18638300895691

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 1 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 2
Cuda memmory allocated: 168909824
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 140/140 [01:12<00:00,  1.94it/s]
100% 16/16 [00:10<00:00,  1.58it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 2, 'windows': None} | time: 72.41494083404541

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 2 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 4
Cuda memmory allocated: 320780288
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.57it/s]
100% 140/140 [01:14<00:00,  1.87it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 4, 'windows': None} | time: 75.02245330810547

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 4 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 6
Cuda memmory allocated: 472650752
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.58it/s]
100% 140/140 [01:13<00:00,  1.91it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 6, 'windows': None} | time: 73.59637451171875

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 6 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 8
Cuda memmory allocated: 624521216
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.55it/s]
100% 140/140 [01:14<00:00,  1.89it/s]
100% 16/16 [00:10<00:00,  1.57it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 8, 'windows': None} | time: 74.24964308738708

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 8 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 10
Cuda memmory allocated: 776391680
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.57it/s]
100% 140/140 [01:12<00:00,  1.93it/s]
100% 16/16 [00:10<00:00,  1.48it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 10, 'windows': None} | time: 72.56032252311707

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 10 -->
[1]  [ cases_loop ] Update results into results_small_dtw_segmentation_1gtrends_kohlslatest.csv
[1]  [ cases_loop ] Update errors into errors_small_dtw_segmentation_2gtrends_kohlslatest.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 1
Cuda memmory allocated: 928262144
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.50it/s]
100% 140/140 [01:12<00:00,  1.93it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]]
N windows:  1
Loss:  [0.06184826626122231]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 1, 'windows': None} | time: 72.68090009689331

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 1 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 2
Cuda memmory allocated: 1080132608
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 140/140 [01:14<00:00,  1.88it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]]
N windows:  1
Loss:  [0.06184826626122231]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 2, 'windows': None} | time: 74.50384593009949

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 2 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 4
Cuda memmory allocated: 1232003072
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.55it/s]
100% 140/140 [01:12<00:00,  1.93it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]]
N windows:  1
Loss:  [0.06184826626122231]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 4, 'windows': None} | time: 72.59376668930054

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 4 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 6
Cuda memmory allocated: 1383873536
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 140/140 [01:12<00:00,  1.94it/s]
100% 16/16 [00:10<00:00,  1.57it/s]

---- Returned internal errors ---
Check: [[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]]
N windows:  1
Loss:  [0.06184826626122231]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 6, 'windows': None} | time: 72.36569619178772

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 6 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 8
Cuda memmory allocated: 1535744000
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.57it/s]
100% 140/140 [01:12<00:00,  1.94it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]]
N windows:  1
Loss:  [0.06184826626122231]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 8, 'windows': None} | time: 72.47699117660522

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 8 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 10
Cuda memmory allocated: 1687614464
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 140/140 [01:12<00:00,  1.94it/s]
100% 16/16 [00:10<00:00,  1.55it/s]

---- Returned internal errors ---
Check: [[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]]
N windows:  1
Loss:  [0.06184826626122231]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 10, 'windows': None} | time: 72.37187480926514

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 10 -->
[1]  [ cases_loop ] Update results into results_small_dtw_segmentation_1gtrends_kohlslatest.csv
[1]  [ cases_loop ] Update errors into errors_small_dtw_segmentation_2gtrends_kohlslatest.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 1
Cuda memmory allocated: 1839484928
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 140/140 [01:11<00:00,  1.95it/s]
100% 16/16 [00:10<00:00,  1.58it/s]

---- Returned internal errors ---
Check: [[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]]
N windows:  1
Loss:  [0.0617679327915539]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 1, 'windows': None} | time: 71.94190239906311

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 1 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 2
Cuda memmory allocated: 1991355392
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.57it/s]
100% 140/140 [01:12<00:00,  1.93it/s]
100% 16/16 [00:10<00:00,  1.51it/s]

---- Returned internal errors ---
Check: [[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]]
N windows:  1
Loss:  [0.0617679327915539]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 2, 'windows': None} | time: 72.85191822052002

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 2 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 4
Cuda memmory allocated: 2143225856
0.85
Initialize Windowed Dataset

100% 16/16 [00:11<00:00,  1.43it/s]
100% 140/140 [01:13<00:00,  1.90it/s]
100% 16/16 [00:10<00:00,  1.54it/s]

---- Returned internal errors ---
Check: [[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]]
N windows:  1
Loss:  [0.0617679327915539]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 4, 'windows': None} | time: 73.67748928070068

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 4 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 6
Cuda memmory allocated: 2295096320
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 140/140 [01:12<00:00,  1.92it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]]
N windows:  1
Loss:  [0.0617679327915539]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 6, 'windows': None} | time: 72.97459745407104

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 6 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 8
Cuda memmory allocated: 2446966784
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 140/140 [01:12<00:00,  1.92it/s]
100% 16/16 [00:10<00:00,  1.57it/s]

---- Returned internal errors ---
Check: [[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]]
N windows:  1
Loss:  [0.0617679327915539]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 8, 'windows': None} | time: 72.99121570587158

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 8 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 10
Cuda memmory allocated: 2598837248
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.58it/s]
100% 140/140 [01:11<00:00,  1.95it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]]
N windows:  1
Loss:  [0.0617679327915539]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 10, 'windows': None} | time: 72.05640172958374

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 10 -->
[1]  [ cases_loop ] Update results into results_small_dtw_segmentation_1gtrends_kohlslatest.csv
[1]  [ cases_loop ] Update errors into errors_small_dtw_segmentation_2gtrends_kohlslatest.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75 -->

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15-->
0.2
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 1
Cuda memmory allocated: 2750707712
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 200/200 [01:45<00:00,  1.90it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.003363055532099679, 0.003179269327665679, 0.003210023167775944, 0.0032320123369572683, 0.00294213290035259, 0.002697615491342731, 0.0029315966414287685, 0.002524436975363642, 0.003153060984914191, 0.0024459802720230074, 0.00248247318668291, 0.0025532676721923054, 0.00269606331421528, 0.0025586941133951767, 0.002495738631114364, 0.0025180715281749146, 0.002678322367137298, 0.0021623378386721017, 0.0025436493946472184, 0.002619094357942231]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 1, 'windows': None} | time: 105.48295783996582

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 1 -->
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 2
Cuda memmory allocated: 2902578176
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
100% 200/200 [01:44<00:00,  1.91it/s]
100% 16/16 [00:10<00:00,  1.56it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.003363055532099679, 0.003179269327665679, 0.003210023167775944, 0.0032320123369572683, 0.00294213290035259, 0.002697615491342731, 0.0029315966414287685, 0.002524436975363642, 0.003153060984914191, 0.0024459802720230074, 0.00248247318668291, 0.0025532676721923054, 0.00269606331421528, 0.0025586941133951767, 0.002495738631114364, 0.0025180715281749146, 0.002678322367137298, 0.0021623378386721017, 0.0025436493946472184, 0.002619094357942231]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 2, 'windows': None} | time: 105.030033826828

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 2 -->
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 4
Cuda memmory allocated: 3054448640
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.55it/s]
100% 200/200 [01:42<00:00,  1.94it/s]
100% 16/16 [00:10<00:00,  1.57it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.003363055532099679, 0.003179269327665679, 0.003210023167775944, 0.0032320123369572683, 0.00294213290035259, 0.002697615491342731, 0.0029315966414287685, 0.002524436975363642, 0.003153060984914191, 0.0024459802720230074, 0.00248247318668291, 0.0025532676721923054, 0.00269606331421528, 0.0025586941133951767, 0.002495738631114364, 0.0025180715281749146, 0.002678322367137298, 0.0021623378386721017, 0.0025436493946472184, 0.002619094357942231]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 4, 'windows': None} | time: 103.14549112319946

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 4 -->
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 6
Cuda memmory allocated: 3206319104
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.58it/s]
100% 200/200 [01:43<00:00,  1.93it/s]
100% 16/16 [00:10<00:00,  1.57it/s]

---- Returned internal errors ---
Check: [[0.05571538423100719, 0.003363055532099679, 0.003179269327665679, 0.003210023167775944, 0.0032320123369572683, 0.00294213290035259, 0.002697615491342731, 0.0029315966414287685, 0.002524436975363642, 0.003153060984914191, 0.0024459802720230074, 0.00248247318668291, 0.0025532676721923054, 0.00269606331421528, 0.0025586941133951767, 0.002495738631114364, 0.0025180715281749146, 0.002678322367137298, 0.0021623378386721017, 0.0025436493946472184, 0.002619094357942231]]
N windows:  1
Loss:  [0.05571538423100719]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 6, 'windows': None} | time: 103.81120347976685

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,80.186383,0.055642,0.084736,0.007317,0.050761,...,0.046245,0.143478,[12],[17],"[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'smape': [0.15654293222436605]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05564203326503048, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05564203326503048], 'mse': [0.0847356474804737], 'rmse': [0.007317139726022579], 'mae': [0.05076108762055389], 'sm...",0.055642,0.043357
1,small,20,0.15,0.25,2,72.414941,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
2,small,20,0.15,0.25,4,75.022453,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
3,small,20,0.15,0.25,6,73.596375,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
4,small,20,0.15,0.25,8,74.249643,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
5,small,20,0.15,0.25,10,72.560323,0.055715,0.084791,0.007327,0.050911,...,0.046245,0.143478,[12],[17],"[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]","{'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 'smape': [0.1574534930368639]}","{'loss': [0.04335716189962113], 'mse': [0.07470968570730269], 'rmse': [0.005712777278906348], 'mae': [0.04624464328993451], 'smape': [0.14347842492368218]}","([[0.05571538423100719, 0.004639214927530182, 0.0047550422438819495, 0.0042262455223993, 0.0040955476787140855, 0.003985285181053249, 0.003988236962218902, 0.00399563751748896, 0.00358851404910508, 0.003825643008375274, 0.0034839769318101128, 0.0037300738580857535, 0.0035658668992774828, 0.003989554413627567, 0.0034225827423922184, 0.003716580058348232, 0.0033750606359847423, 0.003708861506311223, 0.003200329118824032, 0.0035826701163646896, 0.003298175718685213]], {'loss': [0.05571538423100719], 'mse': [0.08479100829150704], 'rmse': [0.007326839064016089], 'mae': [0.05091051207008687], 's...",0.055715,0.043357
6,small,20,0.15,0.50,1,72.680900,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
7,small,20,0.15,0.50,2,74.503846,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
8,small,20,0.15,0.50,4,72.593767,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
9,small,20,0.15,0.50,6,72.365696,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
10,small,20,0.15,0.50,8,72.476991,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
11,small,20,0.15,0.50,10,72.371875,0.061848,0.089412,0.008138,0.053461,...,0.048432,0.148742,[12],[17],"[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]","{'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963], 'smape': [0.16336261505236743]}","{'loss': [0.04865905377664603], 'mse': [0.07939097049067194], 'rmse': [0.006412310262999609], 'mae': [0.048432246512494795], 'smape': [0.14874188629066054]}","([[0.06184826626122231, 0.004701407472436715, 0.004872536357392424, 0.004331758516075622, 0.004538548819255084, 0.003920203357535813, 0.00364679452780235, 0.004212329708804775, 0.003907504129788971, 0.0038517601039659765, 0.0035843771474901587, 0.0038034483773766886, 0.0037067388641714516, 0.004302255131603617, 0.0038757169511102673, 0.003857169853290543, 0.0033410660897581173, 0.0035189551251408246, 0.003192957948028509, 0.0037217917311604004, 0.003646534393608038]], {'loss': [0.06184826626122231], 'mse': [0.08941216559262447], 'rmse': [0.008137742136884079], 'mae': [0.05346053063653963],...",0.061848,0.048659
12,small,20,0.15,0.75,1,71.941902,0.061768,0.089605,0.008123,0.051471,...,0.048201,0.149870,[12],[15],"[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]","{'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': [0.1581072754192917]}","{'loss': [0.052885092482028995], 'mse': [0.08294422749606561], 'rmse': [0.006965640545962113], 'mae': [0.04820123576551429], 'smape': [0.14987017162284744]}","([[0.0617679327915539, 0.004668878187658265, 0.005440213185335908, 0.004700578187891681, 0.005097431109918814, 0.0050787846557796, 0.00458070812081652, 0.004515999237940248, 0.004232670155553413, 0.004276060698820012, 0.004372400535170787, 0.004270909428929112, 0.0042192503710144335, 0.004234854510286823, 0.0037069322175479363, 0.003937027221711885, 0.003390206036523783, 0.004318438753086541, 0.004040732846728393, 0.004618068333781723, 0.004301365298618164]], {'loss': [0.0617679327915539], 'mse': [0.08960478487788669], 'rmse': [0.008122930929018522], 'mae': [0.05147128199681271], 'smape': ...",0.061768,0.052885

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 6 -->
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 8
Cuda memmory allocated: 3358189568
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.56it/s]
 28% 56/200 [00:30<01:15,  1.92it/s]

Observaciones:
- El número de épocas más pequeño a partir de los

In [32]:
#results_small = pd.read_csv(file_results_small, index_col=None, header=0)
#errors_small  = pd.read_csv(file_errors_small, index_col=None, header=0)
print(errors_small.shape)
print(results_small.shape)

(0, 7)
(72, 24)

In [ ]:
print("----- ERRORS -----")
print(f"Total error cases: {len(errors_small)}")
display(errors_small.head())
print(f"Total results: {len(results_small)}")
display(results_small.head())

In [ ]:
results_small["best_epochs"]

#### Checking the errors
Checking the error cases to see if they can be fixed within the code for the future

In [ ]:
if already_computed_small:
    display(results_small['windows'].drop_duplicates())

In [ ]:
if (already_computed_small):
    errors_small['n_epochs'] = pd.to_numeric(errors_small['n_epochs'], errors='coerce').astype('Int64')
    errors_small['n_windows'] = pd.to_numeric(errors_small['n_windows'], errors='coerce').astype('Int64')
    errors_small['masked_percent'] = pd.to_numeric(errors_small['masked_percent'], errors='coerce').astype(float)
    errors_small['error'] = errors_small['error'].astype(str)
    print(results_small.dtypes)
    results_small['model_size'] = results_small['model_size'].astype(pd.StringDtype())
    print("--- Second check ---")
    print(results_small.dtypes)

In [ ]:
if already_computed_small:
    display(results_small['windows'].drop_duplicates())

In [ ]:
if errors_small.shape[0] > 0:
    error_small_window_sizes = list(errors_small['window'].drop_duplicates())
    display(error_small_window_sizes)

In [ ]:
if errors_small.shape[0] > 0:
    error_small_mssg =errors_small['error'].astype(str).drop_duplicates()
    display(error_small_mssg)

We see two failures to check within the failures:
1) Windows do no respect the requested distance between sepparated windows (only one with ne next). TODO: check
2) This dataset needs windows bigger than 4 for MOMENT - Small. => 
    => We need:

   - A minimum and maximum variate allowing to ask for windows sizes inside an interval
   - Control within the windows sizes. If we all like this log table, we can save an unique variate (not saving the windows part) just to check if a window has already failed with this error so it does not execute again.
   - ¿Buen TFG un SQL de gestión de errores para DeepVATS? -> Hablar con Víctor

First valid window:

In [ ]:
small_windows = results_small['windows'].drop_duplicates()
print(small_windows.shape)
display(small_windows)

In [ ]:
filtered_windows = small_windows.apply(lambda x: greater_than(x, 5)).apply(sorted)
filtered_windows

A futuros, se observa que, cuando analicemos este dataset, deberemos:
- Usar ventanas mayores que 5, preferiblemente, >= 8.
- Corregir la función de ventanas para que indique en un warning y en una variable el número de ventanas devuelto realmente. Gestionar para que si no se ha devuelto el número de ventanas esperado, se corte el loop ahí en lugar de repetir los mismos expserimentos.

#### Time analysis

In [ ]:
total_time = results_small['time'].sum()
print(f"{total_time} seconds")
print(f"{total_time/60} minutes")
print(f"{total_time/60/60} hours")

In [ ]:
results_small.plot(figsize = (10,4))

In [ ]:
df_time_analysis_small = results_small[[
    "time", 
    "n_epochs", 
    "dataset_percent", 
    "masked_percent", 
    "n_windows", 
    "last_eval_loss", 
    "last_mse"
]]
df_time_analysis_small.plot(figsize = (10,4))

In [ ]:
plot_with_multiple_secondary_y(df_time_analysis_small, ["n_epochs", "time", "n_windows"], ["last_eval_loss", "dataset_percent", "masked_percent", 'last_mse'])

In [ ]:
profile_small_df = df_time_analysis_small.copy(deep = True)

In [ ]:
#profile_small.to_notebook_iframe()

In [ ]:
profile_small_df.head()

In [ ]:
print(profile_small_df.dtypes)

In [ ]:
# Convertir n_epochs y n_windows a enteros, manejando posibles errores
profile_small_df['n_epochs'] = pd.to_numeric(profile_small_df['n_epochs'], errors='coerce').astype('Int64')
profile_small_df['n_windows'] = pd.to_numeric(profile_small_df['n_windows'], errors='coerce').astype('Int64')

# Convertir masked_percent a float, manejando posibles errores
profile_small_df['masked_percent'] = pd.to_numeric(profile_small_df['masked_percent'], errors='coerce').astype(float)

In [ ]:
profile_small = ydp.ProfileReport(profile_small_df, title="Pandas Profiling Report for 'df_time_analysis_small'", explorative=True)

In [ ]:
 plot_correlation(profile_small_df)

A nivel de tiempo, se observa que:

- Apenas afecta el enmascarado, con una correlación negativa con el last loss. Lo mismo ocurre con el n_epochs
- Más tiempo parece hacer crecer el last_loss
- Lo que más influye es el porcentaje de dataset utilizado para el fine_tuning. Más dataset parece hacer empeorar por alguna razón
- El last loss está bastante relacionado con el tiempo dedicado al fine-tuning, como es de esperar. Pero. La correlación es positiva => más last loss => más tiempo.
- El número de ventanas parece ir en contra de bajar el loss.. quizá porque va de la mano del número de ventanas.

### Loss & metrics analysis

A nivel de losses, se observa (sin tener en cuenta mse, rmse, mae, smape): 
- Muy poca relación con el enmascarado, cosa que de primeras sorprende
- Mucha relación con el % de dataset utilizado en el fine-tuning
Por lo tanto,
    - vamos a filtrar el dataset para tener tiempos menores a 8 segundos
y buenos losses.
    - Veamos a partir de qué momento se obtienen unos losses razonables  en %.

In [ ]:
results_small.columns

In [ ]:
df_loss_small = results_small[[
    "time", "n_epochs", "dataset_percent", "masked_percent", "n_windows", 
    "first_eval_loss", "last_eval_loss", "first_mse", "last_mse"
]].copy()

In [ ]:
display(df_loss_small[["first_eval_loss", "last_eval_loss"]])
display(df_loss_small[["first_mse", "last_mse"]])

In [ ]:
df_loss_small["loss_percent"] = (df_loss_small['first_eval_loss']-df_loss_small['last_eval_loss'])*100/(df_loss_small['first_eval_loss'])
df_loss_small["loss_percent"].plot()
df_loss_small["mse_percent"] = (df_loss_small['first_mse']-df_loss_small['last_mse'])*100/(df_loss_small['first_mse'])
df_loss_small["mse_percent"].plot()

In [ ]:
df_loss_small[df_loss_small["loss_percent"] > 0]

In [ ]:
df_loss_small[df_loss_small["time"] < 8]["loss_percent"].plot()
df_loss_small[df_loss_small["time"] < 8]["mse_percent"].plot()

In [ ]:
# Filtrar filas donde "time" es menor a 8 segundos
df_loss_small_best_cases = df_loss_small[df_loss_small["time"] < 8].copy()

print("--------------------- Train -----------------")
# Filtrar los 5 mejores loss_percents
display(df_loss_small_best_cases.sort_values('loss_percent', ascending = False)[:5])
# Filtrar los 5 mejores loss_percent con dataset percent <= 0.25
display(df_loss_small_best_cases[df_loss_small_best_cases['dataset_percent'] < 0.50].sort_values('loss_percent', ascending = False)[:5])
print("---------------------- Eval ------------------")
# Filtrar los 5 mejores loss_percents
display(df_loss_small_best_cases.sort_values('mse_percent', ascending = False)[:5])
# Filtrar los 5 mejores loss_percent con dataset percent <= 0.25
display(df_loss_small_best_cases[df_loss_small_best_cases['dataset_percent'] < 0.50].sort_values('loss_percent', ascending = False)[:5])

In [ ]:
# Convertir n_epochs y n_windows a enteros, manejando posibles errores
profile_small_df = df_loss_small[['time', 'n_epochs', 'dataset_percent', 'masked_percent', 'n_windows', 'loss_train_percent', 'mse_percent']].copy()
profile_small_df.dtypes

In [ ]:
# Convertir n_epochs y n_windows a enteros, manejando posibles errores
profile_small_df['n_epochs'] = pd.to_numeric(profile_small_df['n_epochs'], errors='coerce').astype('Int64')
profile_small_df['n_windows'] = pd.to_numeric(profile_small_df['n_windows'], errors='coerce').astype('Int64')
# Convertir masked_percent a float, manejando posibles errores
profile_small_df['masked_percent'] = pd.to_numeric(profile_small_df['masked_percent'], errors='coerce').astype(float)

In [ ]:
profile_small = ydp.ProfileReport(profile_small_df, title="Pandas Profiling Report for 'df_loss_small'", explorative=True)
plot_correlation(profile_small_df)

#### What if I focus on 0.25 dataset percent?

In [ ]:
profile_small_df_2 = df_time_analysis_small[df_time_analysis_small['dataset_percent'] == 0.25].drop(columns=['dataset_percent', 'time']).copy()

In [ ]:
fprofile_small_df_2.dtypesf

In [ ]:
# Convertir n_epochs y n_windows a enteros, manejando posibles errores
profile_small_df_2['n_epochs'] = pd.to_numeric(profile_small_df_2['n_epochs'], errors='coerce').astype('Int64')
profile_small_df_2['n_windows'] = pd.to_numeric(profile_small_df_2['n_windows'], errors='coerce').astype('Int64')
# Convertir masked_percent a float, manejando posibles errores
profile_small_df_2['masked_percent'] = pd.to_numeric(profile_small_df_2['masked_percent'], errors='coerce').astype(float)

In [ ]:
profile_small_2 = ydp.ProfileReport(profile_small_df_2, title="Pandas Profiling Report for 'df_time_analysis_small' for < 0.25 dataset percent", explorative=True)
plot_correlation(profile_small_df_2)

* Correlación inversa entre masked percent y last loss * => Aumentar masked percent baja last_loss
* => Es parte de lo que queremos!

In [ ]:
#! ls errors*

In [ ]:
print(torch.cuda.memory_allocated())
gc.collect()
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated())

In [ ]:
before = torch.cuda.memory_allocated()
print(before)
moment_small.to('cpu')
for param in moment_small.parameters():
    param.to('cpu')
after = torch.cuda.memory_allocated()
print(after)
print("Mejorado: ", after-before)

## Moment-base

### Download the model

In [ ]:
print("Getting base artifact: ", enc_artifact_base_name)
enc_artifact_base  = wandb_api.artifact(enc_artifact_base_name, type='learner')
moment_base  = enc_artifact_base.to_obj()

### Select parameters

In [ ]:
#total_cases_small      = len(n_epochs_list)*len(dataset_percents)*len(masked_percents)*len(sizes)
#print(f"Total cases: {total_cases_small}")

n_epochs_list_base= [20]
dataset_percents_base  = [0.15, 0.2, 0.3]
masked_percents_base = [ 0.25, 0.5, 0.75]
sizes_base             = [1, 5]

#n_epochs_list_base= [5, 10, 20]
#dataset_percents_base  = [0.25, 0.5]
#masked_percents_base = [ 0.25, 0.5, 0.75]
#sizes_base             = [1, 5, 10]
#total_cases_base = len(n_epochs_list_base)*len(dataset_percents_base)*len(masked_percents_base)*len(sizes)
#print(f"Total cases: {total_cases_base}")
#expected_time = total_time*total_cases_base/total_cases_small
#print(f"Expected time: {expected_time} seconds | {expected_time/60} minutes | {expected_time/60/60} hours")

### Configure files and wether already computed or not

In [ ]:
already_computed_base = False
results_base = None
errors_base = None
file_errors_base = 'errors_base_24012025_1.csv'
file_results_base = 'results_base_24012025_1.csv'
file_errors_base = 'errors_base_24022025_1.csv'
file_results_base = 'results_base_24022025_1.csv'
file_errors_base = 'errors_base_26022025_1'
file_results_base = 'results_base_26022025_1'
file_errors_base = file_errors_base + dataset + version
file_results_base = file_results_base + dataset + version

### Execute cases

In [ ]:
results_base = None
errors_base = None
if already_computed_base:
    results_base = pd.read_csv(file_results_base, index_col=None, header=0)
    errors_base = pd.read_csv(file_errors_base, index_col=None, header=0)
else:
    results_base, errors_base = cases_loop(
        model             = moment_base, 
        n_epochs_list     = n_epochs_list_base, 
        dataset_percents  = dataset_percents_base, 
        masked_percents = masked_percents_base,
        n_sizes_list      = sizes_base, 
        summarized        = True,
        verbose           = 8,
        save = True,
        file_errors =file_errors_base,
        file_results = file_results_base
    )
    results_base.to_csv(file_results_base, index=False, header=True)
    errors_base.to_csv(file_errors_base, index=False, header=True)
    already_computed_base = True

In [ ]:
print("----- ERRORS -----")
print(f"Total error cases: {len(errors_base)}")
display(errors_base.head())
print(f"Total results: {len(results_base)}")
display(results_base.head())

### Checking the errors

In [ ]:
len(results_base)

In [ ]:
error_base_window_sizes = list(errors_base['windows'].drop_duplicates())
error_base_window_sizes

In [ ]:
error_base_mssg = errors_base['error'].astype(str).drop_duplicates()
error_base_mssg

In [ ]:
base_windows = results_base['windows'].drop_duplicates()
filtered_windows_base = base_windows.apply(lambda x: greater_than(x, 5)).apply(sorted)
filtered_windows_base

#### Time analysis

In [ ]:
df_time_analysis_base = results_base[["time", "n_epochs", "dataset_percent", "masked_percent", "n_windows", "last_train_loss", "last_mse"]]

In [ ]:
plot_with_multiple_secondary_y(df_time_analysis_base, ["n_epochs", "time", "n_windows"], ["last_train_loss", "dataset_percent", "masked_percent", "last_mse"])

In [ ]:
profile_base_df = df_time_analysis_base.copy(deep = True)
profile_base = ydp.ProfileReport(profile_base_df, title="Pandas Profiling Report for 'df_time_analysis_base'", explorative=True)

In [ ]:
plot_correlation(profile_base_df)

#### Loss & metrics analysis

In [ ]:
df_loss_base = results_base[["time", "n_epochs", "dataset_percent", "masked_percent", "n_windows", "first_train_loss", "last_train_loss", "first_mse", "last_mse"]].copy()
df_loss_base["loss_percent"] = (df_loss_base['first_train_loss']-df_loss_base['first_train_loss'])*100/(df_loss_base['first_train_loss'])
df_loss_base["loss_percent"].plot()
df_loss_base["mse_percent"] = (df_loss_base['first_mse']-df_loss_base['last_mse'])*100/(df_loss_base['first_mse'])
df_loss_base["mse_percent"].plot()

In [ ]:
df_loss_base[df_loss_base["time"] < 8]["loss_percent"].plot()
df_loss_base[df_loss_base["time"] < 8]["mse_percent"].plot()

In [ ]:
df_loss_base[df_loss_base["time"] < 20]

In [ ]:
# Filtrar filas donde "time" es menor a 8 segundos
df_loss_base_best_cases = df_loss_base[df_loss_base["time"] < 8].copy()

print("---- Mejoras en el entrenamiento ----")
# Filtrar los 5 mejores loss_percents
display(df_loss_base_best_cases.sort_values('loss_percent', ascending = False)[:5])
# Filtrar los 5 mejores loss_percent con dataset percent <= 0.25
display(df_loss_base_best_cases[df_loss_base_best_cases['dataset_percent'] < 0.50].sort_values('loss_percent', ascending = False)[:5])
print("---- Mejoras en la validación  ----")
# Filtrar los 5 mejores loss_percents
display(df_loss_base_best_cases.sort_values('mse_percent', ascending = False)[:5])
# Filtrar los 5 mejores loss_percent con dataset percent <= 0.25
display(df_loss_base_best_cases[df_loss_base_best_cases['dataset_percent'] < 0.50].sort_values('mse_percent', ascending = False)[:5])

In [ ]:
print(torch.cuda.memory_allocated())
gc.collect()
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated())

## Moment-large

### Download de large model

In [28]:
already_computed_large = False
file_errors_large = 'errors_large_03022025_1.csv'
file_results_large = 'results_large_03022025_1.csv'
file_errors_large = 'errors_large_24022025_1.csv'
file_results_large = 'results_large_24022025_1.csv'

In [29]:
if not already_computed_large:
    print("Getting large artifact: ", enc_artifact_large_name)
    enc_artifact_large = wandb_api.artifact(enc_artifact_large_name, type='learner')
    print(enc_artifact_large.name)
    moment_large = enc_artifact_large.to_obj()
    print(count_parameters(moment_large))

Getting large artifact:  mi-santamaria/deepvats/zeroshot-moment-large-embedding:v0
zeroshot-moment-large-embedding:v0

wandb: Downloading large artifact zeroshot-moment-large-embedding:v0, 1321.42MB. 1 files...
wandb:   1 of 1 files downloaded.
Done. 0:0:4.0

341248520

In [30]:
#total_cases_small      = len(n_epochs_list)*len(dataset_percents)*len(masked_percents)*len(sizes)
#print(f"Total cases: {total_cases_small}")
#total_cases_base = len(n_epochs_list_base)*len(dataset_percents_base)*len(masked_percents_base)*len(sizes)
#print(f"Total cases: {total_cases_base}")
#expected_time = total_time*total_cases_base/total_cases_small
#print(f"Expected time: {expected_time} seconds | {expected_time/60} minutes | {expected_time/60/60} hours")

n_epochs_list_large     = [20]
dataset_percents_large  = [0.15, 0.2, 0.3] # No tendría sentido porque sería como hacer lo mismo que con mvp
masked_percents_large = [0.25, 0.5, 0.75]
sizes_large             = [1, 5, 10]
print(f"Total cases: {len(n_epochs_list)*len(dataset_percents)*len(masked_percents)*len(sizes)}")

Total cases: 72

In [31]:
torch.cuda.memory_allocated()
torch.cuda.set_device(1)
torch.cuda.current_device()

1

In [32]:
results_large = None
errors_large = None
if already_computed_large:
    results_large = pd.read_csv(file_results_large, index_col=None, header=0)
    errors_large = pd.read_csv(file_errors_large, index_col=None, header=0)
else:
    results_large, errors_large = cases_loop(
        model             = moment_large, 
        n_epochs_list     = n_epochs_list_large,
        dataset_percents  = dataset_percents_large, 
        masked_percents = masked_percents_large, 
        n_sizes_list      = sizes_large, 
        summarized        = True,
        save              = True,
        file_errors       =  file_errors_large,
        file_results      = file_results_large
    )
    already_computed_large = True

0.15
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 1
Cuda memmory allocated: 0
0.85
Initialize Windowed Dataset

100% 16/16 [00:11<00:00,  1.36it/s]
100% 140/140 [01:20<00:00,  1.73it/s]
100% 16/16 [00:10<00:00,  1.55it/s]

---- Returned internal errors ---
Check: [[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]]
N windows:  1
Loss:  [0.005508984104380943]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 1, 'windows': None} | time: 81.35347080230713

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.04634,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 1 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 5
Cuda memmory allocated: 1479061504
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 140/140 [01:18<00:00,  1.78it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]]
N windows:  1
Loss:  [0.005489605027833022]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 5, 'windows': None} | time: 79.45229077339172

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.04634,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.04634,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 5 -->
--> epoch 20, dataset_percent 0.15, mask 0.25
 sizes 10
Cuda memmory allocated: 2941083648
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 140/140 [01:18<00:00,  1.78it/s]
100% 16/16 [00:10<00:00,  1.54it/s]

---- Returned internal errors ---
Check: [[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]]
N windows:  1
Loss:  [0.005489605027833022]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.25, 'n_windows': 10, 'windows': None} | time: 79.31017756462097

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.04634,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.04634,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.04634,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25, sizes 10 -->
[1]  [ cases_loop ] Update results into results_large_24022025_1.csv
[1]  [ cases_loop ] Update errors into errors_large_24022025_1.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.25 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 1
Cuda memmory allocated: 4403105792
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.51it/s]
100% 140/140 [01:18<00:00,  1.78it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]]
N windows:  1
Loss:  [0.006221671174898802]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 1, 'windows': None} | time: 79.47731876373291

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 1 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 5
Cuda memmory allocated: 5865127936
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 140/140 [01:17<00:00,  1.80it/s]
100% 16/16 [00:10<00:00,  1.54it/s]

---- Returned internal errors ---
Check: [[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]]
N windows:  1
Loss:  [0.006221671174898802]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 5, 'windows': None} | time: 78.69387173652649

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 5 -->
--> epoch 20, dataset_percent 0.15, mask 0.5
 sizes 10
Cuda memmory allocated: 7327150080
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 140/140 [01:18<00:00,  1.79it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]]
N windows:  1
Loss:  [0.006221671174898802]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.5, 'n_windows': 10, 'windows': None} | time: 78.66888093948364

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5, sizes 10 -->
[1]  [ cases_loop ] Update results into results_large_24022025_1.csv
[1]  [ cases_loop ] Update errors into errors_large_24022025_1.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.5 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 1
Cuda memmory allocated: 8789172224
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 140/140 [01:18<00:00,  1.78it/s]
100% 16/16 [00:10<00:00,  1.52it/s]

---- Returned internal errors ---
Check: [[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]]
N windows:  1
Loss:  [0.006831323626101948]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 1, 'windows': None} | time: 79.34097075462341

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 1 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 5
Cuda memmory allocated: 10251194368
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 140/140 [01:17<00:00,  1.80it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]]
N windows:  1
Loss:  [0.006831323626101948]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 5, 'windows': None} | time: 78.31589889526367

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 5 -->
--> epoch 20, dataset_percent 0.15, mask 0.75
 sizes 10
Cuda memmory allocated: 11713216512
0.85
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 140/140 [01:18<00:00,  1.78it/s]
100% 16/16 [00:10<00:00,  1.54it/s]

---- Returned internal errors ---
Check: [[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]]
N windows:  1
Loss:  [0.006831323626101948]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.15, 'masked_percent': 0.75, 'n_windows': 10, 'windows': None} | time: 79.1318883895874

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75, sizes 10 -->
[1]  [ cases_loop ] Update results into results_large_24022025_1.csv
[1]  [ cases_loop ] Update errors into errors_large_24022025_1.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15, mask 0.75 -->

[1]  [ cases_loop ] epoch 20, dataset_percent 0.15-->
0.2
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 1
Cuda memmory allocated: 13175238656
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.52it/s]
100% 200/200 [01:49<00:00,  1.82it/s]
100% 16/16 [00:11<00:00,  1.41it/s]

---- Returned internal errors ---
Check: [[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]]
N windows:  1
Loss:  [0.005489605027833022]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 1, 'windows': None} | time: 110.73980498313904

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 1 -->
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 5
Cuda memmory allocated: 14637260800
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 200/200 [01:48<00:00,  1.84it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]]
N windows:  1
Loss:  [0.005489605027833022]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 5, 'windows': None} | time: 109.72833395004272

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 5 -->
--> epoch 20, dataset_percent 0.2, mask 0.25
 sizes 10
Cuda memmory allocated: 16099282944
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 200/200 [01:49<00:00,  1.83it/s]
100% 16/16 [00:10<00:00,  1.52it/s]

---- Returned internal errors ---
Check: [[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]]
N windows:  1
Loss:  [0.005489605027833022]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.25, 'n_windows': 10, 'windows': None} | time: 110.0598087310791

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25, sizes 10 -->
[1]  [ cases_loop ] Update results into results_large_24022025_1.csv
[1]  [ cases_loop ] Update errors into errors_large_24022025_1.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.25 -->
--> epoch 20, dataset_percent 0.2, mask 0.5
 sizes 1
Cuda memmory allocated: 17561305088
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 200/200 [01:47<00:00,  1.86it/s]
100% 16/16 [00:10<00:00,  1.55it/s]

---- Returned internal errors ---
Check: [[0.006221671174898802, 0.00030797958752373236, 0.00030549646107829175, 0.0003197506037395215, 0.00035111018041789066, 0.00028608940083358904, 0.00030457286484306676, 0.000303818082466023, 0.0003274532598879887, 0.00029584924031951233, 0.000325595627509756, 0.00031439147533092183, 0.0003251369318604702, 0.00032020398102758916, 0.00032643300073686987, 0.0003100825288129272, 0.0002959544770419598, 0.00032870341165107674, 0.000289563956175698, 0.00035550757820601575, 0.00032909616056713275]]
N windows:  1
Loss:  [0.006221671174898802]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.5, 'n_windows': 1, 'windows': None} | time: 108.64223980903625

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.5, sizes 1 -->
--> epoch 20, dataset_percent 0.2, mask 0.5
 sizes 5
Cuda memmory allocated: 19023327232
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.51it/s]
100% 200/200 [01:50<00:00,  1.80it/s]
100% 16/16 [00:10<00:00,  1.51it/s]

---- Returned internal errors ---
Check: [[0.006221671174898802, 0.00030797958752373236, 0.00030549646107829175, 0.0003197506037395215, 0.00035111018041789066, 0.00028608940083358904, 0.00030457286484306676, 0.000303818082466023, 0.0003274532598879887, 0.00029584924031951233, 0.000325595627509756, 0.00031439147533092183, 0.0003251369318604702, 0.00032020398102758916, 0.00032643300073686987, 0.0003100825288129272, 0.0002959544770419598, 0.00032870341165107674, 0.000289563956175698, 0.00035550757820601575, 0.00032909616056713275]]
N windows:  1
Loss:  [0.006221671174898802]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.5, 'n_windows': 5, 'windows': None} | time: 111.75087690353394

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.5, sizes 5 -->
--> epoch 20, dataset_percent 0.2, mask 0.5
 sizes 10
Cuda memmory allocated: 20485349376
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.54it/s]
100% 200/200 [01:50<00:00,  1.81it/s]
100% 16/16 [00:10<00:00,  1.52it/s]

---- Returned internal errors ---
Check: [[0.006221671174898802, 0.00030797958752373236, 0.00030549646107829175, 0.0003197506037395215, 0.00035111018041789066, 0.00028608940083358904, 0.00030457286484306676, 0.000303818082466023, 0.0003274532598879887, 0.00029584924031951233, 0.000325595627509756, 0.00031439147533092183, 0.0003251369318604702, 0.00032020398102758916, 0.00032643300073686987, 0.0003100825288129272, 0.0002959544770419598, 0.00032870341165107674, 0.000289563956175698, 0.00035550757820601575, 0.00032909616056713275]]
N windows:  1
Loss:  [0.006221671174898802]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.5, 'n_windows': 10, 'windows': None} | time: 111.15208625793457

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.5, sizes 10 -->
[1]  [ cases_loop ] Update results into results_large_24022025_1.csv
[1]  [ cases_loop ] Update errors into errors_large_24022025_1.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.5 -->
--> epoch 20, dataset_percent 0.2, mask 0.75
 sizes 1
Cuda memmory allocated: 21947371520
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 200/200 [01:53<00:00,  1.76it/s]
100% 16/16 [00:10<00:00,  1.52it/s]

---- Returned internal errors ---
Check: [[0.006831323626101948, 0.0003900923300534487, 0.00034278843777428846, 0.0003941229548217962, 0.0003797858749749139, 0.00031488128115597647, 0.0003615259669459192, 0.00033155496603285426, 0.0003602951255743392, 0.0003098274228250375, 0.00035387675670790487, 0.0004095059310202487, 0.0003393393933947664, 0.0003588949937693542, 0.0003282086523540784, 0.0004276878145901719, 0.0003790379934798693, 0.0003492610667308327, 0.00030691195170220455, 0.00042068279399245514, 0.0003936291570425965]]
N windows:  1
Loss:  [0.006831323626101948]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.75, 'n_windows': 1, 'windows': None} | time: 114.69981217384338

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.75, sizes 1 -->
--> epoch 20, dataset_percent 0.2, mask 0.75
 sizes 5
Cuda memmory allocated: 23409393664
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 200/200 [01:51<00:00,  1.80it/s]
100% 16/16 [00:10<00:00,  1.53it/s]

---- Returned internal errors ---
Check: [[0.006831323626101948, 0.0003900923300534487, 0.00034278843777428846, 0.0003941229548217962, 0.0003797858749749139, 0.00031488128115597647, 0.0003615259669459192, 0.00033155496603285426, 0.0003602951255743392, 0.0003098274228250375, 0.00035387675670790487, 0.0004095059310202487, 0.0003393393933947664, 0.0003588949937693542, 0.0003282086523540784, 0.0004276878145901719, 0.0003790379934798693, 0.0003492610667308327, 0.00030691195170220455, 0.00042068279399245514, 0.0003936291570425965]]
N windows:  1
Loss:  [0.006831323626101948]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.75, 'n_windows': 5, 'windows': None} | time: 111.77909183502197

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.75, sizes 5 -->
--> epoch 20, dataset_percent 0.2, mask 0.75
 sizes 10
Cuda memmory allocated: 24871415808
0.8
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.53it/s]
100% 200/200 [01:51<00:00,  1.80it/s]
100% 16/16 [00:10<00:00,  1.52it/s]

---- Returned internal errors ---
Check: [[0.006831323626101948, 0.0003900923300534487, 0.00034278843777428846, 0.0003941229548217962, 0.0003797858749749139, 0.00031488128115597647, 0.0003615259669459192, 0.00033155496603285426, 0.0003602951255743392, 0.0003098274228250375, 0.00035387675670790487, 0.0004095059310202487, 0.0003393393933947664, 0.0003588949937693542, 0.0003282086523540784, 0.0004276878145901719, 0.0003790379934798693, 0.0003492610667308327, 0.00030691195170220455, 0.00042068279399245514, 0.0003936291570425965]]
N windows:  1
Loss:  [0.006831323626101948]
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.2, 'masked_percent': 0.75, 'n_windows': 10, 'windows': None} | time: 111.87285614013672

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.75, sizes 10 -->
[1]  [ cases_loop ] Update results into results_large_24022025_1.csv
[1]  [ cases_loop ] Update errors into errors_large_24022025_1.csv

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2, mask 0.75 -->

[1]  [ cases_loop ] epoch 20, dataset_percent 0.2-->
0.3
--> epoch 20, dataset_percent 0.3, mask 0.25
 sizes 1
Cuda memmory allocated: 26333437952
0.7
Initialize Windowed Dataset

100% 16/16 [00:10<00:00,  1.52it/s]
  0% 0/320 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/macu/work/dvats/encoder.py", line 3620, in fine_tune_moment_mix_windows
    losses, self.model = self.fine_tune_moment_train_mix_windows_(use_moment_masks, save_best_or_last, loss_pre = loss_pre, lr_scheduler_max_lr = lr_scheduler_max_lr, lr_scheduler_num_warmup_steps = lr_scheduler_num_warmup_steps)
  File "/home/macu/work/dvats/encoder.py", line 3513, in fine_tune_moment_train_mix_windows_
    self.best_model_state   = {k: v.clone().detach().cpu() for k, v in self.model.state_dict().items()}
  File "/home/macu/work/dvats/encoder.py", line 3513, in <dictcomp>
    self.best_model_state   = {k: v.clone().detach().cpu() for k, v in self.model.state_dict().items()}
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 126.00 MiB. GPU 1 has a total capacity of 47.45 GiB of which 79.50 MiB is free. Process 2943600 has 8.17 GiB memory in use. Process 734351 has 1.89 GiB memory in use. Process 753804 has 11.22 GiB memory in use. Process 2879578 has 26.09 GiB memory in use. Of the allocated memory 25.89 GiB is allocated by PyTorch, and 4.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Empty DataFrame
Columns: [window, error]
Index: []

---- Returned internal errors ---
Check: []
Failed case | N Errors 0 | N Results 18
--- Internal ---
Returned errors empty

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,windows,error,window
0,small,20,0.3,0.25,1,Unknown,Non registered error,Unknown

--- Concatenated ---

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,windows,error,window
0,small,20,0.3,0.25,1,Unknown,Non registered error,Unknown

Failed case | N Errors 1 | N Results 18
[1]  [ cases_loop ]  case {'model_size': 'small', 'n_epochs': 20, 'dataset_percent': 0.3, 'masked_percent': 0.25, 'n_windows': 1, 'windows': None} | time: 0.0

  0% 0/320 [00:00<?, ?it/s]

,model_size,n_epochs,dataset_percent,masked_percent,n_windows,time,first_train_loss,first_mse,first_rmse,first_mae,...,last_mae,last_smape,windows,best_epochs,train_losses,eval_pre,eval_post,full_result,first_eval_loss,last_eval_loss
0,small,20,0.15,0.25,1,81.353471,0.005509,0.075217,0.005809,0.047054,...,0.046340,0.143272,[12],[8],"[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae': [0.047053668263160486], 'smape': [0.14551310076890167]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005508984104380943, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005508984104380943], 'mse': [0.07521734099571808], 'rmse': [0.0058087571322295375], 'mae'...",0.005509,0.005427
1,small,20,0.15,0.25,5,79.452291,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
2,small,20,0.15,0.25,10,79.310178,0.005490,0.075119,0.005788,0.047127,...,0.046340,0.143272,[12],[8],"[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005427023571428435], 'mse': [0.07473375071024829], 'rmse': [0.005721019893559259], 'mae': [0.046340073251034605], 'smape': [0.14327247248620867]}","([[0.005489605027833022, 0.0004003661332327673, 0.00038391372904048434, 0.0004086718581675086, 0.0003827526161330752, 0.0003798642023217066, 0.00041784969705206877, 0.00038903427464122487, 0.0004188800563237497, 0.00037614449995869236, 0.00040534149021758433, 0.00040835745260535205, 0.0004027254729278086, 0.0003848647627039879, 0.0004151381945121102, 0.00040413754998423556, 0.0003886629752482155, 0.0004013335294855226, 0.0003904727714793158, 0.00040177511566850754, 0.0003864890984134815]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae':...",0.005490,0.005427
3,small,20,0.15,0.50,1,79.477319,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
4,small,20,0.15,0.50,5,78.693872,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
5,small,20,0.15,0.50,10,78.668881,0.006222,0.080175,0.006561,0.049536,...,0.048656,0.149562,[12],[12],"[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]","{'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'mae': [0.04953621035395575], 'smape': [0.15234153670616465]}","{'loss': [0.0060880052424181486], 'mse': [0.07939489625065485], 'rmse': [0.0064183319801541915], 'mae': [0.04865609896022919], 'smape': [0.14956207048067627]}","([[0.006221671174898802, 0.0004165997129998037, 0.0004312851857061365, 0.00044107248166775595, 0.00039097361981735697, 0.0004516841155626545, 0.00048219240125035867, 0.00042087961264769547, 0.00045526660999582546, 0.00039705292303031977, 0.00046836336592345366, 0.00045110800160078464, 0.00041452822396032777, 0.00038615806624875404, 0.000489532709512527, 0.0004352123562836953, 0.0004342917699042508, 0.00047229577778905096, 0.00046063478241973953, 0.0004590216927421612, 0.00039080892955618244]], {'loss': [0.006221671174898802], 'mse': [0.08017519835317474], 'rmse': [0.006561441165072301], 'm...",0.006222,0.006088
6,small,20,0.15,0.75,1,79.340971,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
7,small,20,0.15,0.75,5,78.315899,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
8,small,20,0.15,0.75,10,79.131888,0.006831,0.084293,0.007202,0.048875,...,0.047983,0.149632,[12],[19],"[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]","{'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.04887493581257083], 'smape': [0.15116490605881905]}","{'loss': [0.006579349321327754], 'mse': [0.0827362892368309], 'rmse': [0.006931222596126784], 'mae': [0.04798304989995542], 'smape': [0.14963214567280073]}","([[0.006831323626101948, 0.0005345828696070905, 0.0005201715238009845, 0.0005149727076059207, 0.0004242035049953431, 0.0005127704966331034, 0.0005771225104191606, 0.0004890756905037311, 0.0005120449771181614, 0.0004642580196169937, 0.0004935351982047516, 0.0004970745046323698, 0.00042762875091284513, 0.00045496927954705564, 0.0004795710935598306, 0.00046834057450593846, 0.0004467209458068412, 0.0005402884728807424, 0.0005928823188047058, 0.0005837564713147003, 0.0004212406196789483]], {'loss': [0.006831323626101948], 'mse': [0.08429288231024924], 'rmse': [0.007201710198666671], 'mae': [0.0...",0.006831,0.006579
9,small,20,0.20,0.25,1,110.739805,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
10,small,20,0.20,0.25,5,109.728334,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471
11,small,20,0.20,0.25,10,110.059809,0.005490,0.075119,0.005788,0.047127,...,0.046748,0.144387,[12],[1],"[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]","{'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae': [0.047127172997421474], 'smape': [0.14605195017239758]}","{'loss': [0.005470634733683255], 'mse': [0.07497963191700419], 'rmse': [0.00576806522165256], 'mae': [0.04674754958322719], 'smape': [0.1443868967436141]}","([[0.005489605027833022, 0.00029494679074559826, 0.0002808416193147423, 0.00030893344192008956, 0.00031094368860067333, 0.0002848547126632184, 0.00029574686377600303, 0.00029266240780998485, 0.0002987930209201295, 0.00028447353452065727, 0.0002894408691645367, 0.00028986059514863883, 0.0002963425693451427, 0.0002888283583160955, 0.00030310042566270565, 0.0003034658744581975, 0.00029401289139059373, 0.00031279457471100613, 0.000287724043300841, 0.0003076881308516022, 0.0002937125573225785]], {'loss': [0.005489605027833022], 'mse': [0.07511938580682903], 'rmse': [0.005788256968682478], 'mae'...",0.005490,0.005471

[1]  [ cases_loop ] epoch 20, dataset_percent 0.3, mask 0.25, sizes 1 -->
--> epoch 20, dataset_percent 0.3, mask 0.25
 sizes 5
Cuda memmory allocated: 27795426816
0.7
Initialize Windowed Dataset

OutOfMemoryError: CUDA out of memory. Tried to allocate 126.00 MiB. GPU 1 has a total capacity of 47.45 GiB of which 59.50 MiB is free. Process 2943600 has 8.17 GiB memory in use. Process 734351 has 1.89 GiB memory in use. Process 753804 has 11.22 GiB memory in use. Process 2879578 has 26.11 GiB memory in use. Of the allocated memory 25.91 GiB is allocated by PyTorch, and 4.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [1]:
print("----- ERRORS -----")
print(f"Total error cases: {len(errors_large)}")
display(errors_large.head())
print(f"Total results: {len(results_large)}")
display(results_large.head())
print("------------------")

----- ERRORS -----

NameError: name 'errors_large' is not defined

In [ ]:
print("----- ERRORS -----")
print(f"Total error cases: {len(errors_large)}")
display(errors_large.head())
print(f"Total results: {len(results_large)}")
display(results_large.head())

In [ ]:
before = torch.cuda.memory_allocated()
print(before)
moment_large.to('cpu')
for param in moment_large.parameters():
    param.to('cpu')
after = torch.cuda.memory_allocated()
print(after)
gc.collect()
print("Mejorado: ", after-before)

#### Errors analysis

In [ ]:
if len(errors_large) > 0:
    error_large_window_sizes = list(errors_large['window'].drop_duplicates())
    error_large_window_sizes

In [ ]:
try:
    error_large_mssg = errors_large['error'].astype(str).drop_duplcates()
    display(error_large_mssg)
except Exception as e:
    print(e)

In [ ]:
large_windows = results_large['windows'].drop_duplicates()
print(large_windows.shape)
display(large_windows)

In [ ]:
filtered_windows_large = large_windows.apply(lambda x: greater_than(x, 5)).apply(sorted)
display(filtered_windows_large)

#### Time analysis

In [ ]:
df_time_analysis_large = results_large[["time", "n_epochs", "dataset_percent", "masked_percent", "n_windows", "last_train_loss", 'last_mse']]
df_time_analysis_large.plot(figsize = (10,4))

In [ ]:
plot_with_multiple_secondary_y(df_time_analysis_large, ["n_epochs", "time", "n_windows"], ["last_train_loss", 'last_mse', "dataset_percent", "masked_percent"])

In [ ]:
profile_large_df = df_time_analysis_large.copy(deep = True)
profile_large = ydp.ProfileReport(profile_large_df, title = "Pandas Profiling Report for 'df_time_analysis_large'", explorative = True)
#profile_large.to_notebook_iframe()

In [ ]:
plot_correlation(profile_large_df)

In [ ]:
df_loss_large = results_large[["time", "n_epochs", "dataset_percent", "masked_percent", "n_windows", "first_train_loss", "last_train_loss", "first_mse", "last_mse"]].copy()

In [ ]:
df_loss_large["loss_train_percent"] = (df_loss_large['first_train_loss']-df_loss_large['last_train_loss'])*100/(df_loss_large['first_train_loss'])
df_loss_large["mse_percent"] = (df_loss_large['first_mse']-df_loss_large['last_mse'])*100/(df_loss_large['first_mse'])
df_loss_large["loss_train_percent"].plot()
df_loss_large["mse_percent"].plot()

In [ ]:
df_loss_large_best_cases = df_loss_large[df_loss_large["time"] < 8].copy()
display(df_loss_large_best_cases)
print("--- train ---")
display(df_loss_large_best_cases[df_loss_large_best_cases["loss_train_percent"] > 0])
print("--- eval ---")
display(df_loss_large_best_cases[df_loss_large_best_cases["mse_percent"] > 0])
display(df_loss_large_best_cases)

In [ ]:
display(df_loss_large_best_cases.sort_values('loss_train_percent', ascending = False))

In [ ]:
before = torch.cuda.memory_allocated()
print(before)
gc.collect()
torch.cuda.empty_cache()
after = torch.cuda.memory_allocated()
print(after)
print(after-before)

In [ ]:
gpu_tensors = []
for obj in gc.get_objects():
    try:
        if isinstance(obj, torch.Tensor) and obj.is_cuda:
            gpu_tensors.append(obj)
    except ReferenceError:
        continue # Omitir los objetos que ya han sido recolectados
print(len(gpu_tensors))

#### Loss & metrics analysis

In [ ]:
#| export
if verbose > 0: print("Execution ended")
beep(1)
beep(1)
beep(1)
beep(1)
beep(1)

In [ ]:
#| hide
if reset_kernel:
    os._exit(00)

# Memory checks

In [ ]:
snapshot = torch.cuda.memory_snapshot()
gpu_tensors = [obj['tensor'] for obj in snapshot if 'tensor' in obj]
for tensor_info in gpu_tensors:
    print(f"Size: {tensor_info['size']}, Device: {tensor_info['device']}, Data type: {tensor_info['dtype']}")
print(gpu_tensors)

In [ ]:
object_types = set()
for obj in snapshot:
    for key in obj.keys():
        object_types.add(key)
print("Tipos de objetos encontrados en el snapshot:")
for obj_type in sorted(object_types):
    print(obj_type)
heavier_obj = None
for obj in snapshot:
    if heavier_obj is None or obj['total_size'] > heavier_obj['total_size']: heavier_obj = obj
print(heavier_obj)

In [ ]:
before = torch.cuda.memory_allocated()
print(torch.cuda.memory_allocated())
gc.collect()
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated())
after = torch.cuda.memory_allocated()
print(after)
print("Mejorado: ", after-before)

In [ ]:
before = torch.cuda.memory_allocated()
print(before)
moment_small.to('cpu')
for param in moment_small.parameters():
    param.to('cpu')
after = torch.cuda.memory_allocated()
print(after)
print("Mejorado: ", after-before)

In [ ]:
before = torch.cuda.memory_allocated()
print(before)
moment_base.to('cpu')
for param in moment_base.parameters():
    param.to('cpu')
after = torch.cuda.memory_allocated()
print(after)
print("Mejorado: ", after-before)

In [ ]:
before = torch.cuda.memory_allocated()
print(before)
moment_large.to('cpu')
for param in moment_large.parameters():
    param.to('cpu')
after = torch.cuda.memory_allocated()
print(after)
print("Mejorado: ", after-before)

In [ ]:
error_small_window_sizes = list(errors_small_hoy['windows'].drop_duplicates())
error_small_window_sizes

In [ ]:
errors_small_hoy

In [ ]:
total_time = results_small_hoy['time'].sum()
print(f"{total_time} seconds")
print(f"{total_time/60} minutes")
print(f"{total_time/60/60} hours")

In [ ]:
df_time_analysis_small = results_small_hoy[["time", "n_epochs", "dataset_percent", "masked_percent", "last_train_loss", 'last_mse']]
df_time_analysis_small.plot(figsize = (10,4))

In [ ]:
plot_with_multiple_secondary_y(df_time_analysis_small, ["n_epochs", "time"], ["last_train_loss", "dataset_percent", "masked_percent", 'last_mse'])

In [ ]:
profile_small_df = df_time_analysis_small.copy(deep = True)

In [ ]:
print("--- Cases ---")
print("--- Number of epochs ---")
print(profile_small_df["n_epochs"].unique())
print("--- Dataset percent ---")
print(profile_small_df["dataset_percent"].unique())
print("--- Dataset masked percent ---")
print(profile_small_df["masked_percent"].unique())

In [ ]:
profile_small_df.head()

In [ ]:
print(profile_small_df.dtypes)

In [ ]:
# Convertir n_epochs y n_windows a enteros, manejando posibles errores
profile_small_df['n_epochs'] = pd.to_numeric(profile_small_df['n_epochs'], errors='coerce').astype('Int64')
#profile_small_df['n_windows'] = pd.to_numeric(profile_small_df['n_windows'], errors='coerce').astype('Int64')

# Convertir masked_percent a float, manejando posibles errores
profile_small_df['masked_percent'] = pd.to_numeric(profile_small_df['masked_percent'], errors='coerce').astype(float)

In [ ]:
profile_small = ydp.ProfileReport(profile_small_df, title="Pandas Profiling Report for 'df_time_analysis_small'", explorative=True)

In [ ]:
 plot_correlation(profile_small_df)